/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.MusicasDao;
import br.ulbra.entity.Musicas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */
public class FrMusicas extends javax.swing.JFrame {

    /**
     * Creates new form FrMusicas
     */
    public FrMusicas() throws SQLException {
        initComponents();
        controlarBt(1);
        setLocationRelativeTo(null);
        controlarBt(1);
        edId.setEnabled(false);
        readJTable();

    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbMusica.getModel();
        modelo.setNumRows(0);
        MusicasDao mdao = new MusicasDao();
        for (Musicas m : mdao.read()) {
            modelo.addRow(new Object[]{
                m.getIdMusica(),
                m.getNomeMusica(),
                m.getArtista(),
                m.getAlbum(),
                m.getGenero(),
                m.getAno(),
                m.getProdutora(),
                m.getDuracao()
            });
        }
    }

    public void readJTableForDesc(String nomeMusica) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbMusica.getModel();
        modelo.setNumRows(0);
        MusicasDao mdao = new MusicasDao();
        for (Musicas m : mdao.readForDesc(nomeMusica)) {
            modelo.addRow(new Object[]{
                m.getIdMusica(),
                m.getNomeMusica(),
                m.getArtista(),
                m.getAlbum(),
                m.getGenero(),
                m.getAno(),
                m.getProdutora(),
                m.getDuracao()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edPesquisaMusica = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pnCad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edNomeMusica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edAlbum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edArtista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edGenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edAno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edProdutora = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edDuracao = new javax.swing.JTextField();
        btAlterarr = new javax.swing.JButton();
        btExcluirr = new javax.swing.JButton();
        btSalva = new javax.swing.JButton();
        btCancelarr = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btPesquisarr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMusica = new javax.swing.JTable();
        btNovoo = new javax.swing.JButton();
        cbTipoMusica = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Músicas");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("MÚSICAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 13, -1, -1));

        edPesquisaMusica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        jPanel1.add(edPesquisaMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 290, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("PESQUISAR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 30));

        pnCad.setBackground(new java.awt.Color(255, 153, 153));
        pnCad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("COD:");
        pnCad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 19, -1, -1));

        edId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edId, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 19, 163, 20));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("NOME  DA MÚSICA");
        pnCad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 24, -1, 10));

        edNomeMusica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edNomeMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 19, 164, 20));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("ÁLBUM");
        pnCad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 57, -1, -1));

        edAlbum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 57, 164, 20));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("ARTISTA");
        pnCad.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 57, -1, -1));

        edArtista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 57, 164, 20));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("GÊNERO");
        pnCad.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 95, -1, -1));

        edGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 95, 164, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("ANO");
        pnCad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 95, -1, -1));

        edAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        edAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edAnoActionPerformed(evt);
            }
        });
        pnCad.add(edAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 95, 164, 20));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("PRODUTORA");
        pnCad.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 133, -1, -1));

        edProdutora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edProdutora, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 133, 164, 20));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("DURAÇÃO");
        pnCad.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 133, -1, -1));

        edDuracao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 133, 164, 20));

        btAlterarr.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btAlterarr.setForeground(new java.awt.Color(153, 51, 0));
        btAlterarr.setText("Alterar");
        btAlterarr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btAlterarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarrActionPerformed(evt);
            }
        });
        pnCad.add(btAlterarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 80, 30));

        btExcluirr.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btExcluirr.setForeground(new java.awt.Color(153, 51, 0));
        btExcluirr.setText("Excluir");
        btExcluirr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btExcluirr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirrActionPerformed(evt);
            }
        });
        pnCad.add(btExcluirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 70, 30));

        btSalva.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btSalva.setForeground(new java.awt.Color(153, 51, 0));
        btSalva.setText("Salvar");
        btSalva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaActionPerformed(evt);
            }
        });
        pnCad.add(btSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 80, 30));

        btCancelarr.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btCancelarr.setForeground(new java.awt.Color(153, 51, 0));
        btCancelarr.setText("Cancelar");
        btCancelarr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btCancelarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarrActionPerformed(evt);
            }
        });
        pnCad.add(btCancelarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 30));

        jPanel1.add(pnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 650, 210));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3279053_music_tone_sing_song_voice_icon.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3279053_music_tone_sing_song_voice_icon.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btPesquisarr.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btPesquisarr.setForeground(new java.awt.Color(153, 51, 0));
        btPesquisarr.setText("PESQUISAR");
        btPesquisarr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btPesquisarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarrActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 80, 40));

        tbMusica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        tbMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD", "NOME", "ARTISTA", "ALBUM", "GENERO", "ANO", "PRODUTORA", "DURAÇÃO"
            }
        ));
        tbMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMusicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMusica);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 580, 90));

        btNovoo.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btNovoo.setForeground(new java.awt.Color(153, 51, 0));
        btNovoo.setText("NOVO");
        btNovoo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btNovoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovooActionPerformed(evt);
            }
        });
        jPanel1.add(btNovoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 70, 30));

        cbTipoMusica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Artista" }));
        jPanel1.add(cbTipoMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edAnoActionPerformed

    private void tbMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMusicaMouseClicked
        controlarBt(3);
        if (tbMusica.getSelectedRow() != -1) {

            edId.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 0).toString());
            edNomeMusica.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 1).toString());
            edArtista.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 2).toString());
            edAlbum.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 3).toString());
            edGenero.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 4).toString());
            edAno.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 5).toString());
            edProdutora.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 6).toString());
            edDuracao.setText(tbMusica.getValueAt(tbMusica.getSelectedRow(), 7).toString());

        }
    }//GEN-LAST:event_tbMusicaMouseClicked

    private void btSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaActionPerformed
        Musicas m = new Musicas();
        try {
           
            MusicasDao mu = new MusicasDao();

            m.setNomeMusica(edNomeMusica.getText());

            m.setArtista(edArtista.getText());

            m.setAlbum(edAlbum.getText());

            m.setGenero(edGenero.getText());

            m.setAno(Integer.parseInt(edAno.getText()));

            m.setProdutora(edProdutora.getText());

            m.setDuracao(Double.parseDouble(edDuracao.getText()));

            mu.create(m);

            readJTable();
            controlarBt(1);
            

        } catch (SQLException ex) {
            Logger.getLogger(FrMusicas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvaActionPerformed
    public void controlarBt(int op) {
        switch (op) {
            case 1:
                pnCad.setVisible(false);
                btSalva.setEnabled(true);
                btAlterarr.setEnabled(false);
                btExcluirr.setEnabled(false);
                break;
            case 2:
                pnCad.setVisible(true);
                btAlterarr.setEnabled(false);
                btExcluirr.setEnabled(false);
                break;
            case 3:
                pnCad.setVisible(true);
                btAlterarr.setEnabled(true);
                btExcluirr.setEnabled(true);
                btSalva.setEnabled(false);
                break;

        }
    }
    private void btExcluirrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirrActionPerformed
        Musicas m = new Musicas();
        try {
            MusicasDao mu = new MusicasDao();
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir essa música?",
                    "Excluir música",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                m.setIdMusica(Integer.parseInt(edId.getText()));
                mu.delete(m);
                controlarBt(1);
                readJTable();
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_btExcluirrActionPerformed

    private void btAlterarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarrActionPerformed
        Musicas m = new Musicas();
        try {
            MusicasDao mu = new MusicasDao();
            m.setNomeMusica(edNomeMusica.getText());
            m.setArtista(edArtista.getText());
            m.setAlbum(edAlbum.getText());
            m.setGenero(edGenero.getText());
            m.setAno(Integer.parseInt(edAno.getText()));
            m.setProdutora(edProdutora.getText());
            m.setDuracao(Double.parseDouble(edDuracao.getText()));
            m.setIdMusica(Integer.parseInt(edId.getText()));
  
            mu.update(m);
            readJTable();
            controlarBt(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: "
                    + e.getMessage());

        }
    }//GEN-LAST:event_btAlterarrActionPerformed

    private void btPesquisarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarrActionPerformed
        try {
            int tipo = 0;
            switch (cbTipoMusica.getSelectedIndex()) {
                case 0:
                    tipo = 0;
                    break;
                case 1:
                    tipo = 1;
            }
            
            if (tipo == 0 ) {
                listarNomeMusica(edPesquisaMusica.getText(), tipo);

            } else  {
                listarArtista(edPesquisaMusica.getText(), tipo);
        
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_btPesquisarrActionPerformed

    public void listarNomeMusica(String nomeMusica, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbMusica.getModel();
        modelo.setNumRows(0);
        MusicasDao mdao = new MusicasDao();
        for (Musicas m : mdao.listarTNomeMusica(nomeMusica, tipo)) {
            modelo.addRow(new Object[]{
                m.getIdMusica(),
                m.getNomeMusica(),
                m.getArtista(),
                m.getAlbum(),
                m.getGenero(),
                m.getAno(),
                m.getProdutora(),
                m.getDuracao()
            });
        }
    }
    public void listarArtista(String nomeMusica, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbMusica.getModel();
        modelo.setNumRows(0);
        MusicasDao mdao = new MusicasDao();
        for (Musicas m : mdao.listarTArtista(nomeMusica, tipo)) {
            modelo.addRow(new Object[]{
                m.getIdMusica(),
                m.getNomeMusica(),
                m.getArtista(),
                m.getAlbum(),
                m.getGenero(),
                m.getAno(),
                m.getProdutora(),
                m.getDuracao()
            });
        }
    }
    private void btCancelarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarrActionPerformed
        controlarBt(1);
    }//GEN-LAST:event_btCancelarrActionPerformed

    private void btNovooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovooActionPerformed
        controlarBt(2);
    }//GEN-LAST:event_btNovooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrMusicas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrMusicas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarr;
    private javax.swing.JButton btCancelarr;
    private javax.swing.JButton btExcluirr;
    private javax.swing.JButton btNovoo;
    private javax.swing.JButton btPesquisarr;
    private javax.swing.JButton btSalva;
    private javax.swing.JComboBox<String> cbTipoMusica;
    private javax.swing.JTextField edAlbum;
    private javax.swing.JTextField edAno;
    private javax.swing.JTextField edArtista;
    private javax.swing.JTextField edDuracao;
    private javax.swing.JTextField edGenero;
    private javax.swing.JTextField edId;
    private javax.swing.JTextField edNomeMusica;
    private javax.swing.JTextField edPesquisaMusica;
    private javax.swing.JTextField edProdutora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCad;
    private javax.swing.JTable tbMusica;
    // End of variables declaration//GEN-END:variables
}
