/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.UsuarioDao;
import br.ulbra.entity.Usuario;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */
public class FrUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrUsuario
     */
    public FrUsuario() throws SQLException {
        initComponents();
        controlarBt(1);
        setLocationRelativeTo(null);
        controlarBt(1);
        edCod.setEnabled(false);
        readJTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        edPesquisar = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        pnCad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbFemi = new javax.swing.JRadioButton();
        rbMasc = new javax.swing.JRadioButton();
        rbOut = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        edEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edNumero = new javax.swing.JTextField();
        edBairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        edSenha = new javax.swing.JPasswordField();
        edSenha2 = new javax.swing.JPasswordField();
        btCancelar = new javax.swing.JButton();
        edFone = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        edCod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        edCep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        edLogradouro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edCidade = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        edEstado = new javax.swing.JTextField();
        brBuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("CADASTRO DE USUÁRIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 210, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, -1, -1));

        tbUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD", "NOME", "CEP", "EMAIL", "SENHA", "TELEFONE", "SEXO", "LOGRADOURO", "BAIRRO", "CIDADE", "ESTADO", "NUMERO"
            }
        ));
        tbUsuario.setMaximumSize(new java.awt.Dimension(0, 0));
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 700, 90));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("PESQUISAR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, 30));

        edPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        edPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(edPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 280, 30));

        btNovo.setText("Novo");
        btNovo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 60, 20));

        pnCad.setBackground(new java.awt.Color(255, 153, 153));
        pnCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnCad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("SEXO:");
        pnCad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        buttonGroup1.add(rbFemi);
        rbFemi.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        rbFemi.setForeground(new java.awt.Color(153, 51, 0));
        rbFemi.setText("FEMININO");
        rbFemi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(rbFemi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 94, -1));

        buttonGroup1.add(rbMasc);
        rbMasc.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        rbMasc.setForeground(new java.awt.Color(153, 51, 0));
        rbMasc.setText("MASCULINO");
        rbMasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(rbMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 100, -1));

        buttonGroup1.add(rbOut);
        rbOut.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        rbOut.setForeground(new java.awt.Color(153, 51, 0));
        rbOut.setText("OUTROS");
        rbOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        rbOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOutActionPerformed(evt);
            }
        });
        pnCad.add(rbOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("TELEFONE:");
        pnCad.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        edEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 220, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("COD:");
        pnCad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 18, -1, -1));

        edNumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 2, true));
        pnCad.add(edNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 180, 20));

        edBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        edBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edBairroActionPerformed(evt);
            }
        });
        pnCad.add(edBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 180, 20));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("BAIRRO");
        pnCad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 20));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("SENHA");
        pnCad.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jLabel11.setText("CONF.SENHA");
        pnCad.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("NÚMERO");
        pnCad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        btSalvar.setText("SALVAR");
        btSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        pnCad.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 60, 20));

        btAlterar.setText("ALTERAR");
        btAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        pnCad.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 70, 20));

        btExcluir.setText("EXCLUIR");
        btExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        pnCad.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 70, 20));

        edSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 220, -1));

        edSenha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 180, 20));

        btCancelar.setText("CANCELAR");
        btCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        pnCad.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 20));

        edFone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        try {
            edFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnCad.add(edFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, 20));

        jLabel12.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 0));
        jLabel12.setText("NOME:");
        pnCad.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 20));

        edNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        edNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNomeActionPerformed(evt);
            }
        });
        pnCad.add(edNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 180, 20));

        edCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 18, 210, 20));

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 0));
        jLabel14.setText("E-MAIL:");
        pnCad.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 52, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 51, 0));
        jLabel15.setText("CEP");
        pnCad.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 20));

        edCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        edCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCepActionPerformed(evt);
            }
        });
        edCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edCepKeyReleased(evt);
            }
        });
        pnCad.add(edCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 20));

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 51, 0));
        jLabel16.setText("LOGRADOURO");
        pnCad.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        edLogradouro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 220, 20));

        jLabel17.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 0));
        jLabel17.setText("CIDADE");
        pnCad.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        edCidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 220, 20));

        jLabel18.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 51, 0));
        jLabel18.setText("ESTADO");
        pnCad.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 30));

        edEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        pnCad.add(edEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 180, 20));

        brBuscar.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        brBuscar.setForeground(new java.awt.Color(153, 51, 0));
        brBuscar.setText("BUSCAR");
        brBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        brBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brBuscarActionPerformed(evt);
            }
        });
        pnCad.add(brBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 61, 60, 20));

        jPanel1.add(pnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 710, 300));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1651925_animal_christmas_deer_rudolf_icon.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, -1));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6334486_glass_lens_loupe_love_magnifying_icon.png"))); // NOI18N
        btPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 70, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordem Crescente", "Ordem Decrescente", "Cidade", "Estado", "Telefone" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        controlarBt(3);
        if (tbUsuario.getSelectedRow() != -1) {
            edCod.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0).toString());
            edNome.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 1).toString());
            edCep.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 2).toString());
            edEmail.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 3).toString());
            edSenha.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 4).toString());
            edSenha2.setText(edSenha.getText());
            edFone.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 5).toString());
            int s = (int) tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 6);
            edLogradouro.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 7).toString());
            edBairro.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 8).toString());
            edCidade.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 9).toString());
            edEstado.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 10).toString());
            edNumero.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 11).toString());
            if (s == 1) {
                rbMasc.setSelected(true);
            } else if (s == 2) {
                rbFemi.setSelected(true);
            } else {
                rbOut.setSelected(true);
            }

        }
    }//GEN-LAST:event_tbUsuarioMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        controlarBt(2);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        try {
            int tipo = 0;
            switch (cbTipo.getSelectedIndex()) {
                case 0:
                    tipo = 0;
                    break;
                case 1:
                    tipo = 1;
                    break;
                case 2:
                    tipo = 2;
                    break;
                case 3:
                    tipo = 3;
                    break;
                case 4:
                    tipo = 4;

            }
            if (tipo == 0 || tipo == 1) {
                listarTCD(edPesquisar.getText(), tipo);

            } else if (tipo == 2) {
                listarCidade(edPesquisar.getText(), tipo);

            } else if (tipo == 3) {
                listarEstado(edPesquisar.getText(), tipo);

            } else if (tipo == 4) {
                listarTelefone(edPesquisar.getText(), tipo);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Usuario u = new Usuario();
        try {
            UsuarioDao ud = new UsuarioDao();
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse cadastro?",
                    "Excluir Registro",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                u.setIdUsu(Integer.parseInt(edCod.getText()));
                ud.delete(u);
                readJTable();
                controlarBt(1);
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        Usuario u = new Usuario();
        try {
            UsuarioDao ud = new UsuarioDao();
            u.setNomeUsu(edNome.getText());
            u.setCep(edCep.getText());
            u.setEmailUsu(edEmail.getText());
            u.setSenhaUsu(edSenha.getText());
            u.setFoneUsu(edFone.getText());
            if (rbMasc.isSelected()) {
                u.setSexoUsu(1);
            } else if (rbFemi.isSelected()) {
                u.setSexoUsu(2);
            } else {
                u.setSexoUsu(3);
            }
            u.setLogradouro(edLogradouro.getText());
            u.setBairro(edBairro.getText());
            u.setCidade(edCidade.getText());
            u.setEstado(edEstado.getText());
            u.setNumero(Integer.parseInt(edNumero.getText()));

            if (edSenha.getText().equals(edSenha2.getText())) {
                u.setIdUsu(Integer.parseInt(edCod.getText()));
                ud.update(u);
                readJTable();
                controlarBt(1);
            } else {
                JOptionPane.showMessageDialog(null,
                        " Você inseriu senhas diferentes!"
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: "
                    + e.getMessage());

        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Usuario u = new Usuario();
        try {
            UsuarioDao ud = new UsuarioDao();
            u.setNomeUsu(edNome.getText());
            u.setCep(edCep.getText());
            u.setEmailUsu(edEmail.getText());
            u.setSenhaUsu(edSenha.getText());
            u.setFoneUsu(edFone.getText());
            if (rbMasc.isSelected()) {
                u.setSexoUsu(1);
            } else if (rbFemi.isSelected()) {
                u.setSexoUsu(2);
            } else {
                u.setSexoUsu(3);
            }
            u.setLogradouro(edLogradouro.getText());
            u.setBairro(edBairro.getText());
            u.setCidade(edCidade.getText());
            u.setEstado(edEstado.getText());
            u.setNumero(Integer.parseInt(edNumero.getText()));
            if (edSenha.getText().equals(edSenha2.getText())) {
                u.setIdUsu(Integer.parseInt(edNumero.getText()));
                ud.create(u);
                readJTable();
                controlarBt(1);
            } else {
                JOptionPane.showMessageDialog(null,
                        " Você inseriu senhas diferentes!"
                );
            }

        } catch (SQLException ex) {
            Logger.getLogger(FrUsuario.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void edBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edBairroActionPerformed

    }//GEN-LAST:event_edBairroActionPerformed

    private void rbOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOutActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        controlarBt(1);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void edNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNomeActionPerformed

    private void edCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCepActionPerformed
    public void buscarCep(String cep) {
        String json;
        try {

            URL url = new URL("http://viacep.com.br/ws/" + cep + "/json");
            URLConnection urlConnection = url.openConnection();
            InputStream is = urlConnection.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(is));

            StringBuilder jsonSb = new StringBuilder();
            br.lines().forEach(l -> jsonSb.append(l.trim()));
            json = jsonSb.toString();
            JOptionPane.showMessageDialog(null, json);
            json = json.replaceAll("[{},:]", "");
            json = json.replaceAll("\"", "\n");
            String array[] = new String[30];
            array = json.split("\n");

            String logradouro = array[7];
            String bairro = array[15];
            String cidade = array[19];
            String estado = array[23];
            edLogradouro.setText(logradouro);
            edBairro.setText(bairro);
            edCidade.setText(cidade);
            edEstado.setText(estado);
        } catch (Exception e) {
//throw new RuntimeException(e);
            JOptionPane.showMessageDialog(null,
                    "Erro"
                    + e.getMessage()
            );
        }

    }
    private void brBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brBuscarActionPerformed
        buscarCep(edCep.getText());

    }//GEN-LAST:event_brBuscarActionPerformed

    private void edCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edCepKeyReleased
        edLogradouro.setText("Aguarde...");
        if (edCep.getText().length() == 8) {
            buscarCep(edCep.getText());
        }

    }//GEN-LAST:event_edCepKeyReleased

    private void edPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPesquisarActionPerformed

    }//GEN-LAST:event_edPesquisarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed

    }//GEN-LAST:event_cbTipoActionPerformed
    public void controlarBt(int op) {
        switch (op) {
            case 1:
                pnCad.setVisible(false);
                btSalvar.setEnabled(true);
                btAlterar.setEnabled(false);
                btExcluir.setEnabled(false);
                break;
            case 2:
                pnCad.setVisible(true);
                btAlterar.setEnabled(false);
                btExcluir.setEnabled(false);
                break;
            case 3:
                pnCad.setVisible(true);
                btAlterar.setEnabled(true);
                btExcluir.setEnabled(true);
                btSalvar.setEnabled(false);
                break;

        }
    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao udao = new UsuarioDao();
        for (Usuario p : udao.read()) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCep(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu(),
                p.getLogradouro(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero()
            });
        }
    }

    public void readJTableForDesc(String nome, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao pdao = new UsuarioDao();
        for (Usuario p : pdao.readForDesc(nome, tipo)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCep(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu(),
                p.getLogradouro(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero()
            });
        }
    }

    public void listarTCD(String nome, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao pdao = new UsuarioDao();
        for (Usuario p : pdao.listarCD(nome, tipo)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCep(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu(),
                p.getLogradouro(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero()
            });
        }
    }

    public void listarCidade(String nome, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao pdao = new UsuarioDao();
        for (Usuario p : pdao.listarTCidade(nome, tipo)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCep(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu(),
                p.getLogradouro(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero()
            });
        }
    }

    public void listarEstado(String nome, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao pdao = new UsuarioDao();
        for (Usuario p : pdao.listarTEstado(nome, tipo)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCep(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu(),
                p.getLogradouro(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero()
            });
        }}
        

    public void listarTelefone(String nome, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao pdao = new UsuarioDao();
        for (Usuario p : pdao.listarTTelefone(nome, tipo)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCep(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu(),
                p.getLogradouro(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero()
            });
        }}
    

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrUsuario().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(FrUsuario.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brBuscar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTextField edBairro;
    private javax.swing.JTextField edCep;
    private javax.swing.JTextField edCidade;
    private javax.swing.JTextField edCod;
    private javax.swing.JTextField edEmail;
    private javax.swing.JTextField edEstado;
    private javax.swing.JFormattedTextField edFone;
    private javax.swing.JTextField edLogradouro;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edNumero;
    private javax.swing.JTextField edPesquisar;
    private javax.swing.JPasswordField edSenha;
    private javax.swing.JPasswordField edSenha2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel pnCad;
    private javax.swing.JRadioButton rbFemi;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JRadioButton rbOut;
    private javax.swing.JTable tbUsuario;
    // End of variables declaration//GEN-END:variables
}
